/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DigitalTwinRouteImport } from './routes/digital-twin'
import { Route as ExplainabilityRouteImport } from './routes/explainability'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as ResponseRouteImport } from './routes/response'
import { Route as TrafficRouteImport } from './routes/traffic'
import { Route as ValidationRouteImport } from './routes/validation'
import { Route as WhatIfRouteImport } from './routes/what-if'
import { Route as WorldModelRouteImport } from './routes/world-model'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTwinRoute = DigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainabilityRoute = ExplainabilityRouteImport.update({
  id: '/explainability',
  path: '/explainability',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponseRoute = ResponseRouteImport.update({
  id: '/response',
  path: '/response',
  getParentRoute: () => rootRouteImport,
} as any)
const TrafficRoute = TrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatIfRoute = WhatIfRouteImport.update({
  id: '/what-if',
  path: '/what-if',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldModelRoute = WorldModelRouteImport.update({
  id: '/world-model',
  path: '/world-model',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/explainability': typeof ExplainabilityRoute
  '/forecast': typeof ForecastRoute
  '/response': typeof ResponseRoute
  '/traffic': typeof TrafficRoute
  '/validation': typeof ValidationRoute
  '/what-if': typeof WhatIfRoute
  '/world-model': typeof WorldModelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/explainability': typeof ExplainabilityRoute
  '/forecast': typeof ForecastRoute
  '/response': typeof ResponseRoute
  '/traffic': typeof TrafficRoute
  '/validation': typeof ValidationRoute
  '/what-if': typeof WhatIfRoute
  '/world-model': typeof WorldModelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/explainability': typeof ExplainabilityRoute
  '/forecast': typeof ForecastRoute
  '/response': typeof ResponseRoute
  '/traffic': typeof TrafficRoute
  '/validation': typeof ValidationRoute
  '/what-if': typeof WhatIfRoute
  '/world-model': typeof WorldModelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/digital-twin'
    | '/explainability'
    | '/forecast'
    | '/response'
    | '/traffic'
    | '/validation'
    | '/what-if'
    | '/world-model'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/digital-twin'
    | '/explainability'
    | '/forecast'
    | '/response'
    | '/traffic'
    | '/validation'
    | '/what-if'
    | '/world-model'
  id:
    | '__root__'
    | '/'
    | '/digital-twin'
    | '/explainability'
    | '/forecast'
    | '/response'
    | '/traffic'
    | '/validation'
    | '/what-if'
    | '/world-model'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DigitalTwinRoute: typeof DigitalTwinRoute
  ExplainabilityRoute: typeof ExplainabilityRoute
  ForecastRoute: typeof ForecastRoute
  ResponseRoute: typeof ResponseRoute
  TrafficRoute: typeof TrafficRoute
  ValidationRoute: typeof ValidationRoute
  WhatIfRoute: typeof WhatIfRoute
  WorldModelRoute: typeof WorldModelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin': {
      id: '/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof DigitalTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explainability': {
      id: '/explainability'
      path: '/explainability'
      fullPath: '/explainability'
      preLoaderRoute: typeof ExplainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/response': {
      id: '/response'
      path: '/response'
      fullPath: '/response'
      preLoaderRoute: typeof ResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traffic': {
      id: '/traffic'
      path: '/traffic'
      fullPath: '/traffic'
      preLoaderRoute: typeof TrafficRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-if': {
      id: '/what-if'
      path: '/what-if'
      fullPath: '/what-if'
      preLoaderRoute: typeof WhatIfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world-model': {
      id: '/world-model'
      path: '/world-model'
      fullPath: '/world-model'
      preLoaderRoute: typeof WorldModelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DigitalTwinRoute: DigitalTwinRoute,
  ExplainabilityRoute: ExplainabilityRoute,
  ForecastRoute: ForecastRoute,
  ResponseRoute: ResponseRoute,
  TrafficRoute: TrafficRoute,
  ValidationRoute: ValidationRoute,
  WhatIfRoute: WhatIfRoute,
  WorldModelRoute: WorldModelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
